### ISSUE TITLE
Adapt probes to rucio/rucio#5804

### ISSUE THREAD

**Issue by dchristidis** [rucio/probes#108]
`record_gauge()` does not exist anymore and calls to it need to be adapted.

**Comment by ericvaandering** [comment]
Any objection to adding a record_gauge function to the probe_utils which matches the old signature to the new? @bari12 @dchristidis

**Comment by ericvaandering** [comment]
So how does this work. Looking into the code I see metrics like `blah.{rse}.set_labels(rse='x')`. I presume prometheus that metric will be `blah` with the dots stripped off and in statsd the metric name will include the "dotted" things?

So the functionality is the same as we had before but the signature is different?

**Comment by ericvaandering** [comment]
Partly done in https://github.com/rucio/probes/pull/110
