### ISSUE TITLE
Probes using SQLAlchemy don't work in 1.31

### ISSUE THREAD

**Issue by ericvaandering** [rucio/probes#112]
Probes meeting this description generate stack traces with the 1.31 rucio code. They are fine in Rucio 1.30.8

I see we freeze the version of the oracle client in the probes build, so that may be the issue. But need to further investigate.

**Comment by ericvaandering** [comment]
I notice that cx_oracle is very old in the probes container: 6.3.1 while 8.3.0 has been available for more than a year and the rest of Rucio uses it. Any reason anyone knows of that we should not?

**Comment by ericvaandering** [comment]
You are still using bare metal?

**Comment by dchristidis** [comment]
In ATLAS, the probes still run on a Puppet-managed VM.

**Comment by ericvaandering** [comment]
OK, that fixes it. Will make a PR.
