### ISSUE TITLE
Probe corrupting ranking value of distances

### ISSUE THREAD

**Issue by bari12** [rucio/probes#16]
There seems to be a probe which corrupts the ranking values in the distances table.
The value should not be negative and also not crazily high, but on ATLAS we are seeing ranges from -1000 to +1000

**Comment by dchristidis** [comment]
I think `check_fts_backlog` is the sole actively-running probe that manipulates the distances. I’ll have a look.

**Comment by dchristidis** [comment]
Problematic probe is no longer in active use.
